### PR TITLE
Updated to support the secp256k1 key

### PR DESCRIPTION
**Pull request by rmspeers**
This should resolve issue #1 fully.
Call this key 'P-256K' for JWA purposes.
Added tests.

### CODE REVIEW

**Comment by rmspeers** [comment]
CC @pfumagalli

**Comment by pfumagalli** [comment]
Sorry, we were on a long holiday weekend here in Germany (and a bit of an internal release in between) :-) 

At a quick glance it looks ok, but I'll tackle it this week if you don't mind?

**Comment by rmspeers** [comment]
No rush on my end -- danke!

**Comment by pfumagalli** [comment]
@rmspeers ... I've updated the docs to reflect that `P-256K` is not a standard `crv` name in JWKs according to the [IANA](https://www.iana.org/assignments/jose/jose.xhtml#web-key-elliptic-curve).

Are *YOU* using JWKs, or just the other formats? If so, I'd like to have a way to make sure that keys using non-standard curves do NOT get serialised in a JWK, as it's not interoperable... Maybe something silly like:

```javascript
if (this.curve == 'secp256k1') throw new Error('Curve secp256k1 can not be used in a JWK');
```

But at the same time, I don't want to disrupt your work if you're using JWKs!

**Comment by pfumagalli** [comment]
@rmspeers: also, r0.0.2 is up on [NPM](https://www.npmjs.com/package/ec-key)

**Pull request merged**
